// export { default as findIndex } from './findIndex';
// export { default as findLastIndex } from './findLastIndex';
// export { default as flatten } from './flatten';
// export { default as sortedIndex } from './sortedIndex';
// export { default as indexOf } from './indexOf';
// export { default as lastIndexOf } from './lastIndexOf';
// export { default as isWindow } from './isWindow';
// export { default as isArrayLike } from './isArrayLike';
// export { default as type } from './type';
// export { default as each } from './each';
// export { default as eq } from './eq';
// export { default as curry } from './curry';
// export { default as dedupe } from './dedupe';
export { default as union } from './union';
export { default as intersect } from './intersect';
export { default as difference } from './difference';
